### ISSUE TITLE
Provide Demo webpage

### ISSUE THREAD

**Issue by kiranpwr1260** [benwinding/ngx-filemanager#13]
Please provide demo page and different operations using this package

**Comment by benwinding** [comment]
There's a demo already here:

site: https://benwinding.github.io/ngx-filemanager/
src: https://github.com/benwinding/ngx-filemanager/tree/master/projects/ngx-filemanager-client-firebase-demo

The problem is that this package requires extensive setup and probably requires refactoring in order to be easily configured and used.
